### ISSUE TITLE
[Win32] Steam 'Init' procedure not found.

### ISSUE THREAD

**Issue by T-Maxxx** [D4edalus/CoD4x_Server#10]
Your autoupdate system also downloading steam_api.dll which contains no function called ["Init"](https://github.com/D4edalus/CoD4x1.8_Server_Pub/blob/master/src/sapi.c#L384).
Here's list of all steam functions for Windows.
[steam_api_exports.txt](https://github.com/D4edalus/CoD4x1.8_Server_Pub/files/322434/steam_api_exports.txt)

**Comment by PureTryOut** [comment]
Any update on this? Has it been looked at, or maybe even been fixed?
