### ISSUE TITLE
Compiling mbedtls fails on Linux

### ISSUE THREAD

**Issue by PureTryOut** [D4edalus/CoD4x_Server#17]
So I'm trying to compile Cod4X for myself, but I'm running into some issues.
First of all, we need to add instructions how to compile the libraries. I figured out I have to enter the lib directories in `src`, so for example `src/tomcrypt`. Then each lib has it's own way of compiling which is not really... useful...
Tomcrypt seems to compile fine by running `build_linux.sh`. Mbedtls has a CMakeLists.txt, so I have to run `mkdir build && cd build; cmake ..; make`. However, it fails at `cmake ..` with
```
CMake Error at CMakeLists.txt:135 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target "mbedtls".
```

Since `mbedtls` and `libtomcrypt` are in practically every distros repo's, it would of course be preferable to compile the system version instead, although I do understand the complications that come from that. This should be fixed anyway. Once it's compilable, I'll update the compilation guide to reflect the new instructions.

**Comment by D4edalus** [comment]
just use the provided makefile and ignore the cmake

2016-07-04 20:03 GMT+02:00 PureTryOut <notifications@github.com>:

**Comment by D4edalus** [comment]
fyi, this is the buildscript for the CI server

whenever you see this:

[image: Inline-Bild 1]
... and your compilation fails you can assume an error on your end ;)

https://github.com/D4edalus/CoD4x_Server/blob/master/.travis.yml


2016-07-04 20:28 GMT+02:00 Dominik Schörkhuber <dschoerk@gmx.at>:

**Comment by T-Maxxx** [comment]
Anything ok on Windows.

**Comment by PureTryOut** [comment]
Ooh wow I didn't see the makefile, my bad, compiles fine now. I'll update the instructions in a PR.
