### ISSUE TITLE
Scriptdocumentation

### ISSUE THREAD

**Issue by D4edalus** [D4edalus/CoD4x_Server#2]
Translate/rewrite scriptdocumentation folder to markup
add information for main_shared

**Comment by florczakraf** [comment]
Working on it. No ETA since I work full time. I will create PR once I think it's ready for review.

**Comment by florczakraf** [comment]
Here's a demo: https://github.com/florczakraf/CoD4x_Server/blob/script-documentation/scriptdocumentation/script_functions_reference.md

Let me know what you think before I continue my work on it. IMO it should eventually become a wiki article (but due to lack of Github's support for wiki pull request it's better to keep it this way for now).

**Comment by IceNinjaman** [comment]
Well we are always happy if someone is going to help with documentation. Thank you.

**Comment by PureTryOut** [comment]
Good job! That's looking really good already!

**Comment by florczakraf** [comment]
#31 is up for review.

**Comment by PureTryOut** [comment]
Is this fixed by #31 or do you guys also want documentation of all non-Cod4X specific functions? I believe there is a site already that does that, but it would probably be good to have it here as well.

**Comment by T-Maxxx** [comment]
I think, you should keep this issue opened for all new contributors who doesn't know about documentation.

**Comment by PureTryOut** [comment]
Honestly, I disagree. Issues exist to be resolved. If resolved, close it.
If people do not see a folder called `scriptdocumentation` in the main repo, or are not willing to search for documentation, they should honestly not create mods in the first place.

If needed, you could add a link to the `scriptdocumentation` folder in the README and the wiki, but don't keep an open issue around just to tell people there is documentation.

**Comment by D4edalus** [comment]
if necessary we can ask ppl for a few lines of documentation in the pullrequests :)
