### ISSUE TITLE
Bug download iwd file.

### ISSUE THREAD

**Issue by icekobrin** [D4edalus/CoD4x_Server#21]
Hi all.
There is a bug with the download cards.
Example.
Mod fs_game mods/ace mp_cod4_torn card
Cvarlist
http://pastebin.com/DnEcgvVp
Calculate Checksum of referenced files
http://pastebin.com/rHtJa7TH
No Checksum of the file 
usermaps/mp_cod4_torn/mp_cod4_torn.iwd
Do not have this file in dvar sv_referencedIwdNames  and sv_referencedIwds
OS version http://puu.sh/pWA51/dbb42a369b.png
Sorry for bad English.

**Comment by icekobrin** [comment]
Files in usermaps/mp_cod4_torn http://puu.sh/pVZYx/81e9162075.png
The bug persists with all custom maps

**Comment by D4edalus** [comment]
did you give it a try without the mod ?

**Comment by T-Maxxx** [comment]
> Mod fs_game mods/ace

**Comment by D4edalus** [comment]
well .. i ment an empty mod :)
in general custom maps work fine with cod4x

as tmaxx said, also check the file permissions. the user running the server must be able to read the files

**Comment by icekobrin** [comment]
All custom maps 644 http://puu.sh/pWTba/af9e8d4cc8.png

**Comment by icekobrin** [comment]
which does not see the files.
http://puu.sh/pWTCV/0186e2fa9a.png

**Comment by IceNinjaman** [comment]
Which version? The one here one github?

**Comment by icekobrin** [comment]
Version http://puu.sh/pXI2U/9df6007b5c.png

**Comment by IceNinjaman** [comment]
Well the question is how it works with current development build.

**Comment by florczakraf** [comment]
I can confirm that the issue is still present in current master.

**Comment by icekobrin** [comment]
On the version from the repository, no problems downloading iwd files. Close issue.
