### ISSUE TITLE
Screenshot processing

### ISSUE THREAD

**Issue by florczakraf** [D4edalus/CoD4x_Server#22]
Hey. Recently I tried to make use of the `sv_screenshotArrivedCmd`. I wrote a python script to extract meta-data from the screenshot and draw it on the picture itself. Script does it's job, however I experience the lag on the server each time a new screenshot has arrived. It's _local_ lag -- not shared between other game servers I run on the same machine (i.e. only server that's processing screenshots at the time is affected). The lag is noticeable even without lagometer on -- server freezes for a moment so players experience _teleporting_. 

Here's short video to visualize the issue: https://www.youtube.com/watch?v=FgIVT6_pOhc (you can see spikes on the lagometer at the moment of console outputting `Screenshot for client ... saved to screenshots/...`).

Here are my questions:
1. Have you actually tested this feature? :smirk: 
2. Is it normal that there is such a huge overhead for creating new process with `execv`? (I couldn't find reliable source on the net.)
3. Am I doing something wrong?

More info:
I can provide my script if needed, although the issue exists even with empty python script:
```python
#!/usr/bin/python3
if __name__ == '__main__':
   pass
```
or this c program :smirk::
```c
int main()
{
    return 0;
}
```

**Comment by IceNinjaman** [comment]
Hi there,
I have to admit to not having tested this feature. Isn't it fork() + execv() ?
If your cod4server process start to lag it is probably caused by a function call which does block for some time. Maybe fork() is doing this? Although fork() is part of many daemons you can find on *nix systems. There a little bit lag is maybe not the issue? I don't really know how to do it better.
Creating a new thread to fork() then?

**Comment by T-Maxxx** [comment]
fork() and execv() are very expensive operations. But yeah, forking in other thread should do the trick.

**Comment by D4edalus** [comment]
imho it would be best to just have a plugin callback

2016-07-17 0:30 GMT+02:00 Max <notifications@github.com>:

**Comment by IceNinjaman** [comment]
In current version it is replaced by creating a new thread and invoking system(). Would be nice to know if it works and if it works better. You need however this library for screenshots you can find on forum.

**Comment by florczakraf** [comment]
Alright, I will try to give it a go tonight.

**Comment by florczakraf** [comment]
Did not help at all (tested with empty c program as screenshot processor). I noticed that you now wait till player sees someone to take a screenshot :+1:

**Comment by IceNinjaman** [comment]
You are saying it still doing lag?

**Comment by florczakraf** [comment]
That's exactly what I'm saying.

**Comment by IceNinjaman** [comment]
Okay well then I have no idea how to improve it. Is your host weak in general?

**Comment by florczakraf** [comment]
Don't think so.
CPU: Intel Xeon E3 1245v2	4 cores/ 8 threads	3.4 GHz+
RAM: 32GB DDR3
DISK: 2 x 2 TB SATA (soft raid)
We host some cod4 server, ts, some webtools, and a minecraft server there. Low resource usage.

**Comment by IceNinjaman** [comment]
Okay I still can't do anything if launching a new process does load the whole system so much.

**Comment by florczakraf** [comment]
It doesn't load whole system, that's the point. It only makes the server that's currently receiving screenshots lag.

**Comment by D4edalus** [comment]
https://github.com/D4edalus/CoD4x_Server/commit/8a0a312bf32cb7510f79d1abeb833b36e7191f43

added a plugin callback to enable a more leightweight screenshot processing and avoid manual parsing.
