### ISSUE TITLE
kicking reason for gsc "kick" command

### ISSUE THREAD

**Issue by D4edalus** [D4edalus/CoD4x_Server#23]
Add possibility to give an optional kick reason from gsc

https://github.com/D4edalus/CoD4x_Server/blob/0446cdad5bd19dd9d08cb7733965a5cf6c433fb2/src/scr_vm_functions.c#L1901-L1917

**Comment by T-Maxxx** [comment]
#24 Done.

**Comment by D4edalus** [comment]
thx
