### ISSUE TITLE
kickall command

### ISSUE THREAD

**Issue by D4edalus** [D4edalus/CoD4x_Server#25]
we were asked for a kickall command:
https://cod4x.me/forum/thread-221-post-849.html#pid849

kick command:
https://github.com/D4edalus/CoD4x_Server/blob/3ac725f30caeef9a8390c874b6033397b50d3067/src/sv_cmds.c#L1251

**Comment by T-Maxxx** [comment]
Forgot about auto close feature, sorry :)
