### ISSUE TITLE
Empty for loop body.

### ISSUE THREAD

**Issue by T-Maxxx** [D4edalus/CoD4x_Server#27]
Bug?
https://github.com/D4edalus/CoD4x_Server/blob/master/src/sv_cmds.c#L151

**Comment by D4edalus** [comment]
no i dont think so
the for skips all numbers, if no number is found the whole string is skipped which is recognized by the following if (cuz the string is \0 terminated)

**Comment by T-Maxxx** [comment]
Looks weird... Maybe 'while(not number) then ++i'?
