### ISSUE TITLE
Script function: StrRepl

### ISSUE THREAD

**Issue by florczakraf** [D4edalus/CoD4x_Server#28]
Hey, while working on #2 I had to test some functions. I found a bug in `StrRepl`: it returns source string concatenated with result.

#### Reproduction:
The following code:
```c
source = "Foo bar qux.";
result = StrRepl(source, "Foo", "foo");
self iprintln("Source: " + source);
self iprintln("Result: " + result);
```
results with:
![result](https://cloud.githubusercontent.com/assets/9034451/17085775/e8b4110a-51e0-11e6-8b08-f6792efb461f.gif)

**Comment by T-Maxxx** [comment]
Found bug:
[Here](https://github.com/D4edalus/CoD4x_Server/blob/master/src/qshared.c#L359) - Q_strlcat called with cpylimit = 0 and [here](https://github.com/D4edalus/CoD4x_Server/blob/master/src/qshared.c#L339) - 0 means "copy whole string".
