### ISSUE TITLE
GSC funs for pressed player buttons

### ISSUE THREAD

**Issue by D4edalus** [D4edalus/CoD4x_Server#3]
Similar to `if ( self FragButtonPressed() ) ...` a function to query all possible player buttons as a GSC function would be nice.

The needed info can be read bitwise from the buttons variable in gclient_t
https://github.com/D4edalus/CoD4x1.8_Server_Pub/blob/0446cdad5bd19dd9d08cb7733965a5cf6c433fb2/src/player.h#L395-L399
decode what bits correspond to what key.

qboolean PlayerButtonPressed(gclient_t* player, uint btnIndex) ... or something similar
maybe also methods for specific keys like PlayerForwardButtonPressed 

when finished register the new function as a script command, so it is callable from gsc
https://github.com/D4edalus/CoD4x1.8_Server_Pub/blob/0446cdad5bd19dd9d08cb7733965a5cf6c433fb2/src/scr_vm_main.c#L47-L51

**Comment by T-Maxxx** [comment]
Made it almost year ago as plugin to 1.7a. Do you want pull request?
https://www.youtube.com/watch?v=XPdf4L6p_Cc

**Comment by T-Maxxx** [comment]
Made it almost year ago as a plugin to 1.7a. Do you want pull request?
https://gist.github.com/T-Maxxx/c0b0d353bd0b46ef293c9e940e4be455

**Comment by PureTryOut** [comment]
@T-Maxxx now that is cool. If possible (no clue, not a C/C++ developer ;)), this should be integrated in Cod4X itself, not using a plugin. This could be in a PR after the source code in this repo is updated with the latest version from @D4edalus.

**Comment by T-Maxxx** [comment]
I'm not sure if current commit is latest since "developing in private repo".

**Comment by D4edalus** [comment]
It would be great if you could add those functions. :+1: 
We are going to move our active development soon to this repository. It would be good to wait until that with the pull request.
I will notify you here once that is done.

**Comment by D4edalus** [comment]
@T-Maxxx the code is now up to date, and we have moved our active development to this repo

**Comment by T-Maxxx** [comment]
@D4edalus Great. Thanks. I'll make pull request soon.

**Comment by T-Maxxx** [comment]
Can be closed.
