### ISSUE TITLE
Clear out buildscripts

### ISSUE THREAD

**Issue by PureTryOut** [D4edalus/CoD4x_Server#34]
Currently, the repository holds 5 seperate build scripts, for 2 different platforms (Windows and Linux). This could be changed back to 2.

`build_elf.sh` and `build_mach-o.sh` don't seem to work at all on Linux, and since they are bash scripts (I'm assuming anyway, because of the `.sh` extension) these are useless. `build_updateable_elf.sh` seems to be the only correct one, but it's name is a bit vague. Could this be changed to `build_linux.sh`?

For Windows there are currently 2 scripts: one for official builds with auto updating enabled, and one for manually (developer) compiled builds. It's preferable to have these both combined into 1 script, wich command line options to choose the version. Since most people will be compiling it as a developer build, default should be `developer` and the `official` be secondary. `./build_win32.cmd --official` seems like a good way to do it.

If requested I could probably look into doing this myself, although I have no clue currently how to compile Windows builds anyway.

Of course using Cmake would be preferable (superior) to all of this, as there would be 1 script that can make build scripts for both Windows (MSVC and non-MSVC iirc) and Linux. It could also handle proper git versioning as well (easy to find out reported bugs: just ask people which build number they use as that will be the latest git commit).

**Comment by IceNinjaman** [comment]
build_mach-o.sh has to be compiled from Mac OS X.
build_updateable_elf.sh can upgrae 1.7 clients and the other version can not.

MSVC can't compile it I believe. There are still fragments of GCC inline assembler in sourcecode.

**Comment by PureTryOut** [comment]
Well for Linux there isn't really a different build script. Is there a good reason to keep non-upgrade1.7 clients build anyway?

Can build_mach-o.sh be renamed to `build_macos.sh` or something then? Just to make it clear what it's for. And I'm guessing it's building the Linux version of the server right? Or is it actually making a MacOS version?

MSVC was more an example, maybe later on sometime ;) It's just that CMake makes all this stuff way easier once it's setup properly.

**Comment by D4edalus** [comment]
would speed up compilation compared to the shell scripts because its easier then to compile dependencies and compile targets in parallel. the downside is that it is harder to find the correct compiler settings .. since we have pretty exotic configurations that would probably eat a lot of time.
