### ISSUE TITLE
stats reset with new update

### ISSUE THREAD

**Issue by wkuzma** [D4edalus/CoD4x_Server#39]
I had to shut down the server because ever since the new update 
player stats are reset and stay that way when they join another non cod4x server
I had too many complaints about that.

**Comment by PureTryOut** [comment]
The stats aren't reset, they are just saved to a different directory (a client feature, not a server thing). Copy the `profile` folder from your CoD4 installation directory to `%appdata%\Local\CallofDuty4MW\`, and you will have your stats back.

**Comment by wkuzma** [comment]
Ty that corrected it

**Comment by PureTryOut** [comment]
Please close this since it's resolved.
