### ISSUE TITLE
Cvar for random map rotation

### ISSUE THREAD

**Issue by PureTryOut** [D4edalus/CoD4x_Server#4]
Currently the game only supports a set map rotation, meaning the order you specify in `sv_mapRotation`. Would be great to have an `sv_randomMapRotation` (why is that `sv_` in front anyway?), which randomly rotates through the maps in the list.

**Comment by D4edalus** [comment]
sv = "server" i believe? 
i'm not sure if it makes sense to pick the maps completely randomly, that would include maps can be played twice or more times in a row, and also the frequencies of maps in general wouldn't be uniform.

**Comment by PureTryOut** [comment]
You could keep track of what maps are played already, and only allow a map to be played if it hasn't been played *that* rotation. Basically just create an internal array of the maps in `sv_randomMapRotation`, and randomly choose a map. Once the map is loaded take it out of the array. Continue this till the array is empty, and then fill the array again.

It's easy talking for me since I'm just an user, but seems reasonably easy to me.

Isn't that `sv` redundant? Could it maybe be taken out? Or is this done to keep it clear in code?

**Comment by D4edalus** [comment]
the prefixes are useful to categorize commands
what you are describing would be a permutation (like shuffling cards). problem remains between two permutations.

**Comment by PureTryOut** [comment]
You mean if you rotated once, how to make sure the first map of the next rotation isn't the same map? Don't you have a variable somewhere that holds the previous map? If so, just check if the next chosen random map is the same as the previous one. If it is, try a new random map.

**Comment by PureTryOut** [comment]
If it helps anything, I have some `.gsc` code (I can't exactly remember the name of the guy who gave it to me, and the old Iceops forums are down so I can't check) that currently does it for me in `localized_english_iw07.iwd`, but of course it would be preferable to just have it as a variable in Cod4X.

```
init(){
	level.mapPool = strtok("mp_bo2mir;mp_bo2cargo;mp_box_hjacked;mp_chateau;mp_ctan;mp_mbdepot;mp_pow_rld;mp_tigertown_v2;mp_toujane_beta;mp_brecourt_v2;mp_killhouse;mp_shipment;mp_cargoship;mp_vacant;mp_farm;mp_overgrown;mp_convoy;mp_crash;mp_backlot;mp_crossfire;mp_citystreets;mp_strike;mp_fav;mp_karachi;mp_rundown;mp_scrapyard;mp_skidrow;mp_highrise;mp_inv;mp_modern_rust;mp_mw2_term;mp_sbase;mp_storm_b;mp_nuketown;mp_firingrange_v2;mp_4hanoi;mp_summit;;mp_qmx_matmata;",";");
	level thread randomRotation();
}

randomRotation(){
	wait 5;
	newmap = level.mapPool[randomInt(level.mapPool.size)];
	while(newmap == level.script)
		newmap = level.mapPool[randomInt(level.mapPool.size)];
	setDvar("sv_maprotationCurrent","map " + newmap);
}
```

Although I don't think it checks for playing same map twice in a row and frequency of maps played like you said.

**Comment by T-Maxxx** [comment]
I think, I can take a look on it. The problem is C library function rand() is not providing uniform distribution of results.

**Comment by IceNinjaman** [comment]
Com_RandomBytes()

**Comment by D4edalus** [comment]
picking maps purely by a random distribution at all doesn't make sense as i explained above. same maps might appear twice in a row, or with only one map in between etc.

example set of maps: A, B, C, D

using permutations of the full set
B C A D, C A B D <-- good
B C A D, D A C B <-- bad (D appears twice in a row)

using any random distribution:
A, A, A, A, A, A <-- bad, and is perfectly possible

therefore i would prefer permutations .. or some other smart algorithm that assures some spacing between equal maps.

idea extended: having a probability of appearance per map might be also cool, such that popular maps can appear more often.

**Comment by IceNinjaman** [comment]
Removing maps from sv_maprotationcurrent in random order. That is all you have to do.

**Comment by T-Maxxx** [comment]
This variable just copied from sv_maprotation so deleting c from abcd will affect map sequence a bit and thats not a random

**Comment by IceNinjaman** [comment]
It is a random rotation which is duplicate free.

**Comment by T-Maxxx** [comment]
In vanilla cod its not random, its a sequence based on sv_maprotation. Did you changed something?

**Comment by D4edalus** [comment]
removing random items from the rotation is a good idea. if we remove like 50% of the maps it should feel random and duplicates are avoided.

**Comment by T-Maxxx** [comment]
... And might happen we will never play on map XXX or play it extremely rare.
I think it's better to rebuild whole sv_maprotationcurrent int completely random sequence of maps (having in mind different gametypes for one map)

**Comment by PureTryOut** [comment]
So... Building an array of some sorts of all maps specified by the server admin sounds good. Removing the map out of the array when the map is being played/done. When the array is empty, fill it with new maps. You just have to check that the last map being played of that array isn't the randomly picked map of the new array. The second map of the new array doesn't really matter anymore. Should be relatively easy I would think, right...?
