### ISSUE TITLE
Only allow players with steamid's

### ISSUE THREAD

**Issue by bykidi** [D4edalus/CoD4x_Server#41]
Hi guys.
Is there any way to force every player on server to have steam running in the background?
The reason i want that is that i want to ban peoples on server by steamid, not by their guids.
(sorry if my london feels a bit of russian, which is)

**Comment by PureTryOut** [comment]
There currently isn't a method to do that, but you could write a plugin to do it. The Steam ID's are different then the non-Steam ID's.

**Comment by D4edalus** [comment]
use a gsc script to drop all clients having and invalid steamid?

https://github.com/D4edalus/CoD4x_Server/blob/afe463199fea13177ff9f47be7446560e6d40346/src/scr_vm_functions.c#L71

2016-08-13 11:55 GMT+02:00 PureTryOut <notifications@github.com>:

**Comment by PureTryOut** [comment]
Isn't this more something a plugin should do? I would think you only use gsc to change or enhance gameplay in any way.

**Comment by PureTryOut** [comment]
Since this is not related to the core of the server, this should probably be closed.

**Comment by bykidi** [comment]
gsc scripts, plugins... why not just add this thing as server var?
cl_allowonlysteamids "1"

**Comment by IceNinjaman** [comment]
I am working on it at the moment.

**Comment by bykidi** [comment]
Now that's what i wanted to hear :D :dancers:

**Comment by IceNinjaman** [comment]
It is implemented now with latest steam library and server version.

**Comment by bykidi** [comment]
Closed. Thanks so much!

**Comment by PureTryOut** [comment]
@IceNinjaman for the next time. If you mention the words "Fixes #41" (where #41 is the number of an issue), or "Resolves #41", it will automatically close the related issue once the pull request is merged.

Another good reason to start using pull requests instead of pushing directory to the main repository. Seriously, get used to using pull requests.

**Comment by Kingwolf123** [comment]
What is the  CVAR which enables this feature?

**Comment by T-Maxxx** [comment]
sv_steamgroup

**Comment by bykidi** [comment]
@T-Maxxx thats for ignoring password feature, am i right?
he asks for this exact one, dropping clients that don't use steam

**Comment by T-Maxxx** [comment]
I don't know. I just saw this dvar added in latest commit. Obviously, it requires some client improvements which I have no access. And I don't know what exactly should be in this dvar. Looks like steam group id (as string) and player must be a member of this group.

**Comment by PureTryOut** [comment]
As taken from @IceNinjaman on the [CoD4X forum](https://cod4x.me/forum/thread-384-post-1485.html#pid1485):

```
Cvar sv_steamforce
Value 0: Don't require players having Steam running. This works until now and it is still recommended. This is default value.
Value 1: Require every player entering the server having Steam running.
Value 2: Same as 1 but abandoning playerid. Playerid will be replaced with the steam id.

Cvar sv_steamgroup
Value is the 64 bit identifier of a steam group.

Using the value Steamgroup together with g_password will restrict players from joining server without having a valid password or being member of the steamgroup.
```
