### ISSUE TITLE
About cg_hudCompassSize

### ISSUE THREAD

**Issue by OrigiTosko** [D4edalus/CoD4x_Server#46]
Hi,
About the patch: I have put in my server the version and I have just known that the comand "cg_hudCompassSize" is limitated at value 1 in the clients configurations, i have just tried to use that command in _globallogic.gsc, with the command self setClientDvars ("cg_hudCompassSize", "1.4" ); however i havent worked, i want to know why it isn´t possible to modificate it, who can i fix the patch Cod4x or force this command for all clients configs.

Thanks for read.

**Comment by D4edalus** [comment]
compassSize

**Comment by OrigiTosko** [comment]
I can not understand your response answer.

**Comment by D4edalus** [comment]
afaik your variable doesn't exist. it doesn't exist in the stock client and it doesn't exist in the 1.8x client (i just checked both). the variable "compassSize" does exist, and is working.

**Comment by OrigiTosko** [comment]
Read all post pelase, "cg_hudCompassSize"
