### ISSUE TITLE
getSpectatorClient()

### ISSUE THREAD

**Issue by D4edalus** [D4edalus/CoD4x_Server#48]
script command:
Gets the player that you are following in spectator
following = self getSpectatorClient();

**Comment by florczakraf** [comment]
Would be nice addition, last weekend I rewrote spectating in gsx script to achieve that :D

**Comment by jumper323213** [comment]
and of course you won't be sharing that florczakraf any time soon or ever.

**Comment by florczakraf** [comment]
Actually, I was about to release it after giving it some refactoring but it's no longer needed since it's been implemented in the CoD4x server (PR is still up: https://github.com/D4edalus/CoD4x_Server/pull/50) in a much nicer way than hacky scripts.

**Comment by D4edalus** [comment]
just for my own curiosity.. how does that work with gsc scripts only?

2016-08-27 15:48 GMT+02:00 Rafał Florczak <notifications@github.com>:

**Comment by florczakraf** [comment]
There you go: https://bitbucket.org/msgaming/cod4_spectating_rework
