### ISSUE TITLE
Compile result is not passed from build script

### ISSUE THREAD

**Issue by florczakraf** [D4edalus/CoD4x_Server#49]
As mentioned here: https://github.com/D4edalus/CoD4x_Server/issues/42#issuecomment-241213625

**Comment by D4edalus** [comment]
fixed 
https://github.com/D4edalus/CoD4x_Server/blob/master/build_updateable_elf.sh#L43

example: 
https://travis-ci.org/D4edalus/CoD4x_Server/builds/154025464

**Comment by PureTryOut** [comment]
As reference, it's fixed in 966c33e19892439c6506a0e71172fd8e4885921d
