### ISSUE TITLE
Add final killcam

### ISSUE THREAD

**Issue by PureTryOut** [D4edalus/CoD4x_Server#52]
I'm not sure if CoD4X will (in the future) also add new .gsc scripts to the base installation, if they change no gameplay mechanics.

If so, I would love to see a final killcam added. A lot of servers (mine as well) are currently already using it but have done so by adding it to `main_shared`, but it would be great to have this available by default using a simple variable. Since it's a server-side thing, this could be added to CoD4X as well without altering any gameplay. From MW2 and onwards every CoD game has had this feature, and I really miss it in CoD4.

Added to this post is version 2.4 (the non-slowmo version, as that one is really buggy) of the final killcam found on the internet. Since it's released to the public domain, this can freely be used under AGPLv3.

[CoD4 final killcam.zip](https://github.com/D4edalus/CoD4x_Server/files/437959/CoD4.final.killcam.zip)

**Comment by D4edalus** [comment]
meh .. i think its enough to provide them in a public repository.

**Comment by PureTryOut** [comment]
Sure thing. A CoD4X repository or should I host it on my account?

**Comment by PureTryOut** [comment]
@D4edalus?
