### ISSUE TITLE
team always auto balance feature?

### ISSUE THREAD

**Issue by ekroot** [D4edalus/CoD4x_Server#54]
Hello, I'd like to know if there is any built in team auto balance command feature which will always make sure the teams have equal amount or similar amount of players for a team?

Don't get me wrong, the built in auto balance does kick in some time after if the teams are unbalance but may be mods can manually trigger the auto balance via a command perhaps? 

Thanks for your help in advance.

**Comment by D4edalus** [comment]
this is easily scriptable in gsc.
take a look here on how to add server commands via gsc
https://github.com/D4edalus/CoD4x_Server/blob/master/scriptdocumentation/scriptcommand_example.txt

2016-08-28 11:06 GMT+02:00 ekroot <notifications@github.com>:

**Comment by ekroot** [comment]
Cheers, Will have a look and let you know. +1:

**Comment by D4edalus** [comment]
from some of my old scripts, i think this should still work

https://gist.github.com/D4edalus/92c2d87903e7589db1ad1a8ddf36574d

2016-08-28 11:16 GMT+02:00 ekroot <notifications@github.com>:

**Comment by PureTryOut** [comment]
Maybe related to this, it would be cool to be able to disable team choosing for players spawning. They would basically always be "autoassigned" to a team, which in theory will always make for fair teams. Of course people can leave and thus making a team unbalanced again, but the already existing auto balance will take care of this.

**Comment by T-Maxxx** [comment]
Whole autobalance system is GSC. I don't think it should be changed here.

**Comment by ekroot** [comment]
I noticed people stick with their friendly players all the time. So when the auto balance kicks in it takes 2,3 unfair rounds with unbalanced teams. 

I don't know if i'm asking too much(not for myself) but it would be cool if this project have a skill based team balanced system as well?

**Comment by PureTryOut** [comment]
GSC based? I did not expect that to be honest. Is there a benefit of keeping it GSC based (except for the time it would take to make) over core (C/C++) based?

**Comment by T-Maxxx** [comment]
Easier to edit.

**Comment by D4edalus** [comment]
faster to write and test. furthermore every non-c-programmer is able to
edit and adapt the code as gsc is much more understandable.

2016-08-31 14:27 GMT+02:00 Max <notifications@github.com>:
