### ISSUE TITLE
Cod4X client crashes with latest steam beta client runned in the background

### ISSUE THREAD

**Issue by bykidi** [D4edalus/CoD4x_Server#57]
http://www.mediafire.com/download/7sw8ed4xw8xbmwi/crashreport.zip
![default](https://cloud.githubusercontent.com/assets/1337953/18110994/a727d2a6-6f24-11e6-820e-bd06992d67b7.PNG)

**Comment by bykidi** [comment]
Downgrading to stable steam update channel fixes the problem, but we should be prepared for new build.

**Comment by IceNinjaman** [comment]
Oh crap. This sounds like i have to get an update out there as soon as possible so people have a chance to update before their game crashes. How long does it take for the steam beta to be released?
It is all only for the reason it displays cod4 x18 instead codmw3 dedicated server.
Quite hacky with an automatic disassembler.

**Comment by bykidi** [comment]
Here is dates of steam stable update being released
16 Aug, 7 Jul, 10 Jun, 5 May, 1 Apr, etc etc.
But beta channel usually updates once per few days, sometimes even every day.
//edit1
Tested on newer build from 31.08.16 - still crashing.

**Comment by IceNinjaman** [comment]
Oh then I am on beta channel too. My steam updates every freaking 2 days. But I am  ot aware to have willingly opted in for it.

**Comment by IceNinjaman** [comment]
Not on the Beta. still getting all time Steam updates xD
