### ISSUE TITLE
Core binary

### ISSUE THREAD

**Issue by T-Maxxx** [D4edalus/CoD4x_Server#9]
Why not include core server binary inside cod4x server executable?

**Comment by PureTryOut** [comment]
You mean the original binary provided by Activision? If so, because it's not allowed by the AGPL3 license. An (A)GPL licensed program may depend on proprietary or different licensed code, but it may not be shipped with it. This is why you will notice @D4edalus removed the server binary and dependencies from the repo.
It's a good reason to try to get more code reverse engineered, and lessen the dependency on the original binary.

**Comment by T-Maxxx** [comment]
Linker loads cod4_lnxded-bin, extracts sections, places them in memory and runs. What about including raw sections (extracted and encrypted) directly to source code, for example, as an array of bytes. Then xxbase_00.iwd will be not needed anymore.

**Comment by PureTryOut** [comment]
I have no clue, I guess that's fine. You'll have to read the AGPL3 license to be sure.

**Comment by T-Maxxx** [comment]
I have read it. Looks like I missed "Do not use copyrighted content in your programs. Even encrypted." part.

**Comment by PureTryOut** [comment]
Not sure if you're being sarcastic or not. If it's allowed, it seems to be a good solution. If not, it would probably be best to reverse engineer more and more and eventually become independent of the original binary.

**Comment by T-Maxxx** [comment]
No, truly. I don't know if license allowed to do this.
I think it will never become independent of the original binary - too much work.

**Comment by PureTryOut** [comment]
Not if you gain enough interest of other developers ;) But yeah, definitely a lot of work. I guess you could try to get it to work like you said, I don't think anyone will complain anyway.

**Comment by IceNinjaman** [comment]
Activision would have even more reasons to complain about it I think.

**Comment by T-Maxxx** [comment]
Oh, its working ^.^
@IceNinjaman But you can hide it as deep as you can.
![image](https://cloud.githubusercontent.com/assets/7836454/16564740/d8e79136-4211-11e6-88a0-f7c07e2079fa.png)

**Comment by T-Maxxx** [comment]
So what is your decision?

**Comment by IceNinjaman** [comment]
Well nice but I am not sure.
Also you have to put that directly into the sections. Or you waste some more memory. As I said before it asks for more problems with ATVI if we directly use their code.

**Comment by T-Maxxx** [comment]
Wastes about 2 mb of statically allocated memory.
As you wish.

**Comment by PureTryOut** [comment]
Best is to not distribute anything of Activision. Requiring the users to provide it theirselves is fine, not if the developers do it, as seen by other projects doing this kind of stuff.

**Comment by T-Maxxx** [comment]
Let people provide their binaries (or other file) is a nightmare. Believe me. I was developer on iw4play project - they provide only their own files and nothing of original game. There was 10 posts per day like "Where to get the game?", "My game is not working".

**Comment by PureTryOut** [comment]
I know, but that's just how it is, the only way to get around legal issues. It's how OpenTTD, OpenRCT2, OpenMW and such work, and they never had legal problems.
Currently we had no people asking about where to get the game files, we just have to make it clear.
